Models/ErrorViewModel.cs
namespace reservaSalas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Usuario.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace reservaSalas.Models
{
    [Table("Usuarios")]
    [Index(nameof(Email), IsUnique=true)]
    public class Usuario
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        [Required(ErrorMessage = "O e-mail é obrigatório.")]
        [EmailAddress(ErrorMessage = "Formato de e-mail inválido.")]
        [StringLength(100, ErrorMessage = "O e-mail deve ter até 100 caracteres.")]
        public string Email { get; set; }
        [Required]
        public bool Administrador { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using reservaSalas.Models;

namespace reservaSalas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using reservaSalas.Interfaces;
using reservaSalas.Models;

namespace reservaSalas.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioService _usuarioService;

        public UsuarioController(IUsuarioService usuarioService)
        {
            _usuarioService = usuarioService;
        }

        public async Task<IActionResult> Index()
        {
            var usuario = await _usuarioService.GetAllAsync();
            return View(usuario);
        }

        public async Task<IActionResult> Details(long id)
        {
            var usuario = await _usuarioService.GetByIdAsync(id);

            if(usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _usuarioService.CreateAsync(usuario);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(usuario);
        }

        public async Task<IActionResult> Edit(long id)
        {
            var usuario = await _usuarioService.GetByIdAsync(id);
            if( usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, Usuario usuario)
        {
            if(id != usuario.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    await _usuarioService.UpdateAsync(usuario);
                    return RedirectToAction(nameof(Index));
                }
                catch (InvalidOperationException ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(usuario);
        }

        public async Task<IActionResult> Delete(long id)
        {
            var usuario = await _usuarioService.GetByIdAsync(id);
            if(usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            await _usuarioService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - reservaSalas</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/reservaSalas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">reservaSalas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - reservaSalas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Usuario/Create.cshtml
@model reservaSalas.Models.Usuario

@{
	ViewData["Title"] = "Cadastrar Usuário";
}

<h1>Cadastrar Usuário</h1>

<form asp-controller="Usuario" asp-action="Create" method="post">
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="form-group">
		<label asp-for="Email" class="control-label">E-mail</label>
		<input asp-for="Email" class="form-control"/>
		<span asp-validation-for="Email" class="text-danger"></span>
	</div>
	<div class="form-group mb-3">
		<label asp-for="Administrador">É administrador?</label>
		<select asp-for="Administrador" class="form-control">
			<option value="false">Não</option>
			<option value="true">Sim</option>
		</select>
	</div>
	<button type="submit" class="btn btn-primary">Cadastrar</button>
	<a asp-action="Index" class="btn btn-secondary">Voltar</a>
</form>

@section Scripts{
	@{
		<partial name ="_ValidationScriptsPartial" />
	}
}

Views/Usuario/Delete.cshtml
@model reservaSalas.Models.Usuario

@{
	ViewData["Title"] = "Excluir usuário";
}

<h1>Excluir usuário</h1>

<h3>Tem certeza que deseja excluir este usuário? </h3>

<div>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">Id:</dt>
		<dd class="col-sm-10">@Model.Id</dd>

		<dt class="col-sm-2">E-mail:</dt>
		<dd class="col-sm-10">@Model.Email</dd>

		<dt class="col-sm-2">Administrador?</dt>
		<dd class="col-sm-10">@(Model.Administrador ? "Sim" : "Não")</dd>
	</dl>
	<form asp-action="Delete">
		<input type="hidden" asp-for="Id" />
		<button type="submit" class="btn btn-danger">Excluir</button>
		<a asp-action="Index" class="btn btn-secondary">Cancelar</a>
	</form>
</div>

Views/Usuario/Details.cshtml
@model reservaSalas.Models.Usuario

@{
	ViewData["Title"] = "Detalhes do usuário";
}

<h1>Detalhes de usuário</h1>

<div>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">Id:</dt>
		<dd class="col-sm-10">@Model.Id</dd>

		<dt class="col-sm-2">E-mail:</dt>
		<dd class="col-sm-10">@Model.Email</dd>

		<dt class="col-sm-2">Administrador?:</dt>
		<dd class="col-sm-10">@(Model.Administrador ? "Sim" : "Não")</dd>
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Editar</a>
	<a asp-action="Index" class="btn btn-secondary">Voltar</a>
</div>

Views/Usuario/Edit.cshtml
@model reservaSalas.Models.Usuario

@{
	ViewData["Title"] = "Editar usuário";
}

<h1>Editar usuário</h1>

<form asp-action="Edit" method="post">
	<input type="hidden" asp-for="Id" />
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="form-group">
		<label asp-for="Email" class="control-label"></label>
		<input asp-for="Email" class="form-control" />
		<span asp-validation-for="Email" class="text-danger"></span>
	</div>
	<div class="form-group mb-3">
		<label asp-for="Administrador" class="control-label">Administrador?</label>
		<select asp-for="Administrador" class="form-control">
			<option value="false">Não</option>
			<option value="true">Sim</option>
		</select>
		<span asp-validation-for="Administrador" class="text-danger"></span>
	</div>
	<button type="submit" class="btn btn-primary">Editar</button>
	<a asp-action="Index" class="btn btn-secondary">Voltar</a>
</form>

@section Scripts{
	@{
		<partial name = "_ValidationScriptsPartial" />
	}
}

Views/Usuario/Index.cshtml
@model IEnumerable<reservaSalas.Models.Usuario>

@{
	ViewData["Title"] = "Lista de Usuário";
}

<h1>Lista de usuários</h1>
<p>
	<a asp-action="Create", class="btn btn-primary">Novo usuário</a>
</p>

<table class="table table-striped">
    <thead>
		<tr>
			<th>Id</th>
			<th>E-mail</th>
			<th>Administrador?</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach(var item in Model)
		{
			<tr>
				<td>@item.Id</td>
				<td>@item.Email</td>
				<td>@(item.Administrador ? "Sim" : "Não")</td>
				<td>
					<a asp-action="Details" class="btn btn-warning" asp-route-id="@item.Id">Detalhes</a>
					<a asp-action="Edit" class="btn btn-success"  asp-route-id="@item.Id">Editar</a>
					<a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Excluir</a>
				</td>
			</tr>
		}
	</tbody>
</table>